services:
  cube:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - cube_data:/app/data
    environment:
      - PORT=4000
      - MIX_ENV=prod
      - DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cube_data:
    driver: local
